#server:
#  port: 8060
#logging:
#  level:
#    root: info
#    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
#  file:
#    path: log
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: host_route
#          uri: http://182.254.192.61:8080
#          predicates:
#            - Path=/buyer-service2/**
#          filters:
#            - StripPrefix=1
#        - id: buyer-service
#          uri: lb://buyer-service
#          predicates:
#            - Path=/buyer/**
#          filters:
#            - StripPrefix=1
#        - id: openapi
#          uri: http://182.254.192.61:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://182.254.192.61:8761/eureka/
#springdoc:
#  swagger-ui:
#    urls:
#      - name: buyer
#        url: /v3/api-docs/buyer
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: buyer
          uri: lb://buyer-service
          predicates:
            - Path=/buyer/**
          filters:
            - StripPrefix=1
            - Auth=true
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的上限
                redis-rate-limiter.burstCapacity: 20
                # 使用SpEL表达式从Spring容器中获取Bean对象
                key-resolver: "#{@hostKeyResolver}"
  redis:
    host: 111.231.5.229
    port: 6379
    password: redis123456aB
  application:
    name: gateway
server:
  port: 8060
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://182.254.192.61:8761/eureka/