server:
  port: 8060
logging:
  level:
    root: info
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
  file:
    path: log
spring:
  application:
    name: gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: false
#            lower-case-service-id: true
        routes:
        - id: user-service
#          uri: lb://user-service
          uri: http://172.17.0.4:8080
          predicates:
          - Path=/user-service/**
          filters:
          - StripPrefix=1
#            filters:
#              - RewritePath=/user-service/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.3:8761/eureka/