server:
  port: 8060
logging:
  level:
    root: info
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
  file:
    path: log
spring:
  application:
    name: gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/**
            filters:
              - StripPrefix=1
#            filters:
#              - RewritePath=/user-service/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: http://182.254.192.61:8761/eureka/